name: Dataset submission/request
description: Submit/request a dataset
title: "[Dataset submission/reguest]: "
labels: ["dataset"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using the ColabFit Exchange!
  # Contact Info
  - type: input
    id: name
    attributes:
      label: Name
      description: Please enter your name
      placeholder: ex. John Smith
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Email
      description: Please enter your email
      placeholder: ex. email@example.com
    validations:
      required: true

  # Dataset Info
  - type: input
    id: dataset-name
    attributes:
      label: Dataset name
      description: "Enter a short, human-readable dataset name to be used when publishing to the ColabFit Exchange\nUse underscores instead of spaces"
      placeholder: "CHON_Smith_2023"
  - type: textarea
    id: authors
    attributes:
      label: Authors
      description: "Enter a comma-separated list of authors\nUse full first names rather than initials, unless author is usually attributed by inital(s)"
      placeholder: ex. John B. Smith
    validations:
      required: true
  - type: textarea
    id: links
    attributes:
      label: Links
      description: Provide links to dataset files and related publications
      placeholder: https://www.example.com/
    validations:
      required: true
  - type: textarea
    id: dataset-description
    attributes:
      label: Dataset description
      description: Provide a human-readable description of the dataset. This will be visible to users on the ColabFit Exchange
      placeholder: "What does this dataset contain?\nWhy was it created?"
    validations:
      required: true

  # File details
  - type: textarea
    id: files
    attributes:
      label: File details
      description: Provide details about accessing the dataset
      placeholder: "ex. 150 zipped CIF files\nTotal size: 200 MB\nPython parsing script available on dataset GitHub repo"

  # Calculations
  - type: dropdown
    id: method
    attributes:
      label: Method
      multiple: true
      description: Calculation level of theory. Select all that apply
      options:
        - DFT (default)
        - CCSD
        - CCSD(T)
        - Other (provide method below)
      default: 0
    validations:
      required: true
  - type: input
    id: method-if-other
    attributes:
      label: Method (other)
      description: If you selected Other, please enter level of theory
    validations:
      required: false

  - type: dropdown
    id: software
    attributes:
      label: Software
      description: Enter software used for property calculations
      options:
        - FHI-aims
        - Gaussian 09
        - Gaussian 16
        - ORCA
        - Psi4
        - Quantum ESPRESSO
        - VASP
        - Other (provide software below)
    validations:
      required: true
  - type: input
    id: software-if-other
    attributes:
      label: Software (other)
      description: "If you selected Other, please enter software used"
    validations:
      required: false
  - type: input
    id: software-version
    attributes:
      label: Software version(s)
      description: Please enter software version, if known
    validations:
      required: false

  - type: textarea
    id: additional-details
    attributes:
      label: Additional details
      description: Please enter additional details of data computation, if known
      placeholder: ex. XC functional, basis set, plane wave cutoff value, k-point grid
    validations:
      required: false

  # Properties
  - type: checkboxes
    id: property-types
    attributes:
      label: Property types
      description: Select properties present in dataset
      options:
        - label: Atomic forces
        - label: Atomization energy
        - label: Band gap
        - label: Cauchy stress
        - label: Formation energy
        - label: Free energy
        - label: Potential energy
        - label: Other/additional

  - type: textarea
    id: property-additional
    attributes:
      label: Other/additional property
      description: If using a property other than one from  <a href="https://materials.colabfit.org/browse/property-definitions">the approved ColabFit list</a>, you should specify an property definition following the format shown <a href="https://github.com/gpwolfe/colabfit-data/blob/main/examples/example_property_definitions.py"> in the ColabFit standard </a>
    validations:
      required: false

  - type: textarea
    id: property-details
    attributes:
      label: Property details
      description: Enter details for each property; units, per-atom, any additional details
      placeholder: "ex. potential-energy: units=eV, per-atom=false"
    validations:
      required: true

  # Configurations
  - type: input
    id: elements
    attributes:
      label: Elements
      description: Enter elements as comma-separated list of chemical symbols
      placeholder: ex. C, H, O, N
    validations:
      required: true
  - type: input
    id: num-configs
    attributes:
      label: Number of Configurations
      description: Enter number of configurations contained in dataset
    validations:
      required: true
  - type: textarea
    id: config-names
    attributes:
      label: Naming convention
      description: If your configurations have names, please describe where their names can be found
      placeholder: 'ex. File headers contain key "config_name"'

  - type: textarea
    id: config-sets
    attributes:
      label: Configuration sets
      description: "Configuration sets are used to define a conceptual grouping over a collection of atomic configurations. This can be done by regex matching on specified keys. If you are unsure how to do this, or do not know how the data should be grouped, leave this section blank."
      placeholder: "Specify a key to match on, a regex, and a description of the configuration set:\nname, bulk_*_crystal, Bulk configurations of various perfect crystals\nname, md_trajectory_*, Snapshots from an MD trajectory"
  - type: textarea
    id: config-labels
    attributes:
      label: Configuration labels
      description: "Configuration labels can be attached to your data to improve interpretability. This can be done by regex matching on specified keys. If you are unsure how to do this, or do not know how the data should be labeled, leave this section blank."
      placeholder: "Specify a key to match on, a regex, and a label:\n*surface* \n Slab configurations with various Miller indices\n*vacancy* Bulk configurations with at least one vacancy defect."

  # License and permission
  - type: input
    id: license
    attributes:
      label: Distribution license
      description: The license under which the content is distributed
      placeholder: ex. Creative Commons Zero
    validations:
      required: true

  # Verify permission
  - type: checkboxes
    id: permissions
    attributes:
      label: Permissions
      description: Only applicable if planning to upload data files
      options:
        - label: I confirm that I have the necessary permissions to submit this dataset
          required: false
